# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Sobre o CEAC
    url: /
    weight: 10
  - name: Projetos
    url: /#papers
    weight: 11
  - name: Publicações
    url: /#talks
    weight: 12
  - name: Cursos
    url: /#news
    weight: 13
  - name: Novidades
    url: experience/
    weight: 20
  - name: Membros
    url: projects/
    weight: 30
  - name: Fale conosco
    url: teaching/
    weight: 40
